Add support for building gprmake, gprbind and gprlib through this repository  and its Makefile. (configure --with-gnat-source-dir): new command line switch (src/gprmake_dummies.c): Moved from the gprmake-2006 branch in the GNAT  repository, so that we can more easily build it in the Makefile to be able  to link gprmake, gprbind and gprlib (Makefile): Add new targets to build the other tools
git-svn-id: svn+ssh://svn.eu.adacore.com/Dev/trunk/gprmake@12499 936e1b1b-40f2-da11-902a-00137254ae57

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="src/gprconfig.ads"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os HOST LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os HOST GNAT_SOURCE_DIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -784,6 +784,11 @@ fi
 if test -n "$ac_init_help"; then
 
   cat <<\_ACEOF
+
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-gnat-source-dir=<dir>    Directory that contains the GNAT sources
 
 _ACEOF
 fi
@@ -1329,8 +1334,32 @@ test -n "$target_alias" &&
   program_prefix=${target_alias}-
 HOST=$host
 
+   echo "$as_me:$LINENO: checking GNAT sources" >&5
+echo $ECHO_N "checking GNAT sources... $ECHO_C" >&6
 
-          ac_config_files="$ac_config_files src/sdefault.ads"
+# Check whether --with-gnat-source-dir or --without-gnat-source-dir was given.
+if test "${with_gnat_source_dir+set}" = set; then
+  withval="$with_gnat_source_dir"
+  GNAT_SOURCE_DIR=$withval
+else
+  GNAT_SOURCE_DIR="gnat"
+fi;
+   if ( test -f $GNAT_SOURCE_DIR/prj.ads ) then
+       echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+   else
+       echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+       { { echo "$as_me:$LINENO: error: \"GNAT sources not found in '$GNAT_SOURCE_DIR'. Check the --with-gnat-source-dir switch\"" >&5
+echo "$as_me: error: \"GNAT sources not found in '$GNAT_SOURCE_DIR'. Check the --with-gnat-source-dir switch\"" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+
+
+
+
+
+                    ac_config_files="$ac_config_files src/gprconfig-sdefault.ads gnat.gpr"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -1881,7 +1910,8 @@ for ac_config_target in $ac_config_targets
 do
   case "$ac_config_target" in
   # Handling of arguments.
-  "src/sdefault.ads" ) CONFIG_FILES="$CONFIG_FILES src/sdefault.ads" ;;
+  "src/gprconfig-sdefault.ads" ) CONFIG_FILES="$CONFIG_FILES src/gprconfig-sdefault.ads" ;;
+  "gnat.gpr" ) CONFIG_FILES="$CONFIG_FILES gnat.gpr" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
@@ -1978,6 +2008,7 @@ s,@target_cpu@,$target_cpu,;t t
 s,@target_vendor@,$target_vendor,;t t
 s,@target_os@,$target_os,;t t
 s,@HOST@,$HOST,;t t
+s,@GNAT_SOURCE_DIR@,$GNAT_SOURCE_DIR,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
